M7R0
I(pmatrixX,%)anythingG6"F%[gl!"%!!!#*"$"$""!F&"""F&F'F&F'F&F&F%,
I%pLHSX,F$F%F%[gl!"%!!!#*"$"$z+6&%#J1G%#L1G%#l1G%#m1G\[[[[[][[[[[nF'\[[\[[\[[[[
[n!"#\[[][[[[[[[[nF'[[[[[[[[[\[[lF'F&,.*&F-""#F/F'F'**F-F'%#L3GF'F/F'-I$cosG6$%
*protectedG%(_syslibG6#,&%#q1GF'%#q3G!""F'F?*(F-F'F.F'F/F'F0**F5F'F.F'F/F'F6F'F
'*&F/F'F.F3F'F,F'F&z'6%%#J2G%#l2G%#m2G\[[[][[[[[[[nF'[[[[[[[[\[[[lF',(**F5F'FFF
'FGF'-F76#,&%#q2GF'F>F?F'F'*&FFF3FGF'F'FEF',&F4F?FAF'FI,4FAF'*&F5F3F/F'F'*&F5F3
FGF'F'*&F5F3%#m3GF'F'F4F?FIF'*(FTF'%#l3GF'F5F'F0*&FVF3FTF'F'%#J3GF'F%,
I%pRHSX,F$F%F%[gl!"%!!!#*"$"$z)F+\[[\[[\[[[[[nF?\[[][[[[[[[[nF'[[[[[[[[[\[[lF'*
*F-F'-F76#,&F=F'FMF?F'FFF'FGF',2F,F'FAF'F@F?**F-F'F5F'FGF'F6F'F'**FTF'F-F'F5F'F
6F'F'**F-F'F6F'FVF'FTF'F?FfnF'FBF'F&FCFHF&F&z)6&FXF5FVFT\[[\[[\[[[[[nF?\[[][[[[
[[[[nF'[[[[[[[[[\[[lF'F%,
I%alph,0*&z+6(F,F-F.F/FGFT[[][[[[[[][[[wF'\[[[[[[[[][[[wF'[[[[_[[\[[[[[wF'[[[[[
[[[[[[][oF'F'%&dphi1GF'F'*,F-F'-F76#,&%%phi1GF'%%phi2GF?F'FFF'FGF'%&dphi2GF'F'*
,F-F'-F76#,&FjoF'%%phi3GF?F'FVF'FTF'%&dphi3GF'F?*,F-F'F^pF'FVF'FTF'FeoF'F?*&z'6
%FXFVFT\[[[][[[[[[[nF'[[[[[[[[\[[[lF'F'FbpF'F'*,F-F'FgoF'FFF'FGF'FeoF'F'*&FCF'F
\pF'F'F%
