M7R0
I(pmatrixX,%)anythingG6"F%[gl!"%!!!#*"$"$""!F&"""F&F'F&F'F&F&F%,
I%pLHSX,F$F%F%[gl!"%!!!#*"$"$z+6&%#J1G%#L1G%#l1G%#m1G\[[[[[][[[[[nF'\[[\[[\[[[[
[n!"#\[[][[[[[[[[nF'[[[[[[[[[\[[lF'F&,.*&F-""#F/F'F'**F-F'%#L3GF'F/F'-I$cosG6$%
*protectedG%(_syslibG6#,&%#q1GF'%#q3G!""F'F?*(F-F'F.F'F/F'F0**F5F'F.F'F/F'F6F'F
'*&F/F'F.F3F'F,F'F&z'6%%#J2G%#l2G%#m2G\[[[][[[[[[[nF'[[[[[[[[\[[[lF',(**F5F'FFF
'FGF'-F76#,&%#q2GF'F>F?F'F'*&FFF3FGF'F'FEF',&F4F?FAF'FI,4%#J3GF'*&F5F3F/F'F'*&F
5F3FGF'F'*&F5F3%#m3GF'F'FIF'*(FUF'%#l3GF'F5F'F0F4F?FAF'*&FWF3FUF'F'F%,
I%pRHSX,F$F%F%[gl!"%!!!#*"$"$z)F+\[[\[[\[[[[[nF?\[[][[[[[[[[nF'[[[[[[[[[\[[lF'*
*F-F'-F76#,&FMF?F=F'F'FFF'FGF',2FfnF'FBF'**F-F'F6F'FWF'FUF'F?F,F'FAF'F@F?**F-F'
F5F'FGF'F6F'F'**FUF'F-F'F5F'F6F'F'F&FCFHF&F&z)6&FQF5FWFU\[[\[[\[[[[[nF?\[[][[[[
[[[[nF'[[[[[[[[[\[[lF'F%,
I%alph,0*&z+6(F,F-F.F/FGFU[[][[[[[[][[[wF'\[[[[[[[[][[[wF'[[[[_[[\[[[[[wF'[[[[[
[[[[[[][oF'F'%&dphi1GF'F'*,F-F'-F76#,&%%phi2GF?%%phi1GF'F'FFF'FGF'%&dphi2GF'F'*
,F-F'-F76#,&F[pF'%%phi3GF?F'FWF'FUF'%&dphi3GF'F?*,F-F'F^pF'FWF'FUF'FeoF'F?*&z'6
%FQFWFU\[[[][[[[[[[nF'[[[[[[[[\[[[lF'F'FbpF'F'*,F-F'FgoF'FFF'FGF'FeoF'F'*&FCF'F
\pF'F'F%
