M7R0
I(pmatrixX,%)anythingG6"F%[gl!"%!!!#*"$"$""!F&"""F&F'F&F'F&F&F%,
I%pLHSX,F$F%F%[gl!"%!!!#*"$"$z+6&%#J1G%#L1G%#l1G%#m1G\[[[[[][[[[[nF'\[[\[[\[[[[
[n!"#\[[][[[[[[[[nF'[[[[[[[[[\[[lF'F&,.*&F-""#F/F'F'**F-F'%#L3GF'F/F'-I$cosG6$%
*protectedG%(_syslibG6#,&%#q1GF'%#q3G!""F'F?*(F-F'F.F'F/F'F0**F5F'F.F'F/F'F6F'F
'*&F/F'F.F3F'F,F'F&z'6%%#J2G%#l2G%#m2G\[[[][[[[[[[nF'[[[[[[[[\[[[lF',(**F5F'FFF
'FGF'-F76#,&F>F?%#q2GF'F'F'*&FFF3FGF'F'FEF',&F4F?FAF'FI,4FAF'FIF'*(%#m3GF'%#l3G
F'F5F'F0F4F?*&FSF3FRF'F'%#J3GF'*&F5F3FGF'F'*&F5F3FRF'F'*&F5F3F/F'F'F%,
I%pRHSX,F$F%F%[gl!"%!!!#*"$"$z)F+\[[\[[\[[[[[nF?\[[][[[[[[[[nF'[[[[[[[[[\[[lF'*
*F-F'-F76#,&FMF?F=F'F'FFF'FGF',2**F-F'F5F'FGF'F6F'F'F@F?FAF'FfnF'**FRF'F-F'F5F'
F6F'F'**F-F'F6F'FSF'FRF'F?FBF'F,F'F&FCFHF&F&z)6&FUF5FSFR\[[\[[\[[[[[nF?\[[][[[[
[[[[nF'[[[[[[[[[\[[lF'F%,
I%alph,0*&z+6(F,F-F.F/FGFR[[][[[[[[][[[wF'\[[[[[[[[][[[wF'[[[[_[[\[[[[[wF'[[[[[
[[[[[[][oF'F'%&dphi1GF'F'*,F-F'-F76#,&%%phi2GF?%%phi1GF'F'FFF'FGF'%&dphi2GF'F'*
,F-F'-F76#,&F[pF'%%phi3GF?F'FSF'FRF'%&dphi3GF'F?*,F-F'F^pF'FSF'FRF'FeoF'F?*&z'6
%FUFSFR\[[[][[[[[[[nF'[[[[[[[[\[[[lF'F'FbpF'F'*,F-F'FgoF'FFF'FGF'FeoF'F'*&FCF'F
\pF'F'F%,
I&alph1,(FboF?FfoF?F]pF'F%,
I&alph3,&FcpF'FdpF?F%,
I$bet,8*&FcoF'%'ddphi1GF'F'*,F-F'FgoF'FFF'FGF'%'ddphi2GF'F'*,F-F'F^pF'FSF'FRF'%
'ddphi3GF'F?*,F-F'-I$sinG6$F9F:FhoF'FFF'FGF'F\pF3F'*,F-F'-FgqF_pF'FSF'FRF'FbpF3
F?*,F-F'F^pF'FSF'FRF'F`qF'F?*&FepF'FdqF'F'*,F-F'FjqF'FSF'FRF'FeoF3F'*,F-F'FgoF'
FFF'FGF'F`qF'F'*&FCF'FbqF'F'*,F-F'FfqF'FFF'FGF'FeoF3F?F%
